// Subtitle formatting and export utilities

export function formatSecondsToTime(seconds) {
  if (isNaN(seconds) || seconds === null) return "00:00.00";
  const mins = Math.floor(seconds / 60);
  const secs = Math.floor(seconds % 60);
  const ms = Math.floor((seconds % 1) * 100);
  return `${String(mins).padStart(2, '0')}:${String(secs).padStart(2, '0')}.${String(ms).padStart(2, '0')}`;
}

export function parseTimeToSeconds(timeStr) {
  if (!timeStr) return 0;
  const parts = timeStr.trim().split(':');
  if (parts.length === 2) {
    const mins = parseFloat(parts[0]) || 0;
    const secs = parseFloat(parts[1]) || 0;
    return mins * 60 + secs;
  }
  if (parts.length === 3) {
    const hrs = parseFloat(parts[0]) || 0;
    const mins = parseFloat(parts[1]) || 0;
    const secs = parseFloat(parts[2].replace(',', '.')) || 0;
    return hrs * 3600 + mins * 60 + secs;
  }
  return parseFloat(timeStr) || 0;
}

export function formatTimestampToSRT(seconds) {
  const hrs = Math.floor(seconds / 3600);
  const mins = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);
  const ms = Math.floor((seconds % 1) * 1000);
  return `${String(hrs).padStart(2, '0')}:${String(mins).padStart(2, '0')}:${String(secs).padStart(2, '0')},${String(ms).padStart(3, '0')}`;
}

export function formatTimestampToVTT(seconds) {
  const hrs = Math.floor(seconds / 3600);
  const mins = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);
  const ms = Math.floor((seconds % 1) * 1000);
  return `${String(hrs).padStart(2, '0')}:${String(mins).padStart(2, '0')}:${String(secs).padStart(2, '0')}.${String(ms).padStart(3, '0')}`;
}

export function generateSRT(segments) {
  return segments
    .map((seg, index) => {
      const start = formatTimestampToSRT(seg.startTime);
      const end = formatTimestampToSRT(seg.endTime);
      return `${index + 1}\n${start} --> ${end}\n${seg.text.trim()}\n`;
    })
    .join('\n');
}

export function generateVTT(segments) {
  const body = segments
    .map((seg, index) => {
      const start = formatTimestampToVTT(seg.startTime);
      const end = formatTimestampToVTT(seg.endTime);
      return `${index + 1}\n${start} --> ${end}\n${seg.text.trim()}\n`;
    })
    .join('\n');
  return `WEBVTT - Generated by CapVibe AI\n\n${body}`;
}

export function generateTXT(segments, includeTimestamps = true) {
  if (includeTimestamps) {
    return segments
      .map(seg => `[${formatSecondsToTime(seg.startTime)} - ${formatSecondsToTime(seg.endTime)}] ${seg.text}`)
      .join('\n');
  }
  return segments.map(seg => seg.text).join(' ');
}

export function downloadFile(content, filename, mimeType = 'text/plain;charset=utf-8') {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
